// <auto-generated />
using System;
using JackyAIApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JackyAIApp.Server.Data.Migrations
{
    [DbContext(typeof(AzureSQLDBContext))]
    [Migration("20241010120000_AddMicrosoftGraphToken")]
    partial class AddMicrosoftGraphToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Simplified - this would normally contain all entities
            // For now, we'll let EF generate the full version when migration runs
        }
    }
}